### PR TITLE
Restaurant list page

### PR DESCRIPTION
**Pull request by Khemmie-Ray**

### CODE REVIEW

**Review by cherylli — COMMENTED** [review]
I only see a "No Result Page"

**Comment by Khemmie-Ray** [comment]
> 

That was what I saw in the hi-fi design.

**Comment by cherylli** [comment]
sorry what do you mean? I see this in the hi fi design for the list of restaurant. 
image

It was also on the task #65

**Comment by cherylli** [comment]
done in #52

**Pull request closed without merging**
